
import time
def Main():
    print("'Camping Nightmare'")
    #pause
    print("Enter anything to Play")
    #pause
    input() == print("'Greeting Player'")
    time.sleep(2.5)
    name = input("Type your Name:")
    for _ in range(300):
        print(f"'{name}, you're about to venture into the woods'")
        print()
        time.sleep(2.5)
        print("'Your friends recently discover an unknown lake'")
        print()
        time.sleep(3)
        print("'You were invited to camp and fish for a night'")
        print()
        time.sleep(3)
        print("When you're ready type: start")
        print()
        start = input()
        if(start == "start") : 
            print()
            print(f"Eric: 'Goodmorning {name}, late as usual'")
            print()
            time.sleep(2.5)
            print("Susan: 'There you are, slow-poke!!'")
            print()
            time.sleep(2.5)
            print(f"Derek:'{name}, comon on man, the fish aren't gonna bite by the time we get there..'")
            print()
            time.sleep(5)
            print("'Type 1: My bad it took longer than I'd expected to prep,'")
            print()
            print("'Type 2: I do what I want'")
            print()
            Reply = input()
            if(Reply == "1"):
                print()
                print("Derek:'I told yall we shouldn't had brought him along'")
                print()
                time.sleep(2.5)
                print("Susan:'Chill Derek. We all make mistakes'")
                print()
                time.sleep(2.5)
                print("'Derek made you uncomfortable'")
                print()
                time.sleep(2.5)
                print("'What should you do'")
                print()
                time.sleep(2.5)
                print("'Type 1:Go with them'")
                print()
                print("'Type 2:Leave'")
                print()
                print("'Type 3:Fight Derek'")
                print()
                Reply = input()
                if(Reply == "1"):
                    print()
                    print("'The Group venture into the woods for Hours'")
                    print()
                    time.sleep(2.5)
                    print("'As the group gets deeper and deeper into the forest'")
                    print()
                    time.sleep(2.5)
                    print(f"'{name} felt a chill and notice the woods is too quiet'")
                    print()
                    time.sleep(2.5)
                    print("'Yall made it to the lake!'")
                    print()
                    time.sleep(2.5)
                    print("Erik:'We're here finally. Should we set up camp now, later?'")
                    print()
                    time.sleep(2.5)
                    print("Susan:'I rather set up camp now then later'")
                    print()
                    time.sleep(2.5)
                    print("Derek:'Whatever yall want. I'm going, FISHIING!'")
                    print()
                    time.sleep(2.5)
                    print("'Eric decided to help Susan set up camp'")
                    print()
                    time.sleep(2.5)
                    print("'Who should you join?")
                    print()
                    time.sleep(2.5)
                    print("'Type 1: Susan and Eric'")
                    print()
                    print("'Type 2: Derek'")
                    print()
                    Reply = input()
                    if(Reply == "1"): 
                        print("'By the time camp is set up the sun is setting'")
                        print()
                        time.sleep(2.5)
                        print("Eric:'It's getting dark soon and Derek has been gone for awhile. What should we do'")
                        print()
                        time.sleep(2.5)
                        print(f"'Type 1: {name}: Eric, you go find him, I'll stay with Susan'")
                        print()
                        print(f"'Type 2: {name}: Eric you stay with Susan, I'll go look for him")
                        print()
                        Reply = input()
                        if(Reply == "1"):
                            print()
                            print("'Sun is gone. Can't see anything from 20ft away'")
                            print()
                            time.sleep(2.5)
                            print("Sunsan:'I'm starting to get worried, they're both been gone for a min'")
                            print()
                            time.sleep(2.5)
                            print("'Type 1:Comfort Susan'")
                            print()
                            print("'Type 2: Scared Susan'")
                            print()
                            Reply = input()
                            if(Reply == "1"):
                                print()
                                print("Sunsan:'Let's go look for them'")
                                print()
                                time.sleep(2.5)
                                print("'Type 1: Go'")
                                print()
                                print("'Type 2: Stay and wait'")
                                print()
                                Reply = input()
                                if(Reply == "1"):
                                    print()
                                    print(f"'Susan and {name} left camp'")
                                    print()
                                    time.sleep(2.5)
                                    print("'They're a mile from camp'")
                                    print()
                                    time.sleep(2.5)
                                    print("They heard a chilling cry from an unknown creature at camp'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Both of them made a panic run for it'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Congratulation you completed the demo'")
                                    print()
                                    time.sleep(2.5)
                                    Restart = input("Enter anything to retry all demo ending")
                                    if(Restart == "") : Main()
                                else:
                                    print("'You both waited and waited'")
                                    print()
                                    time.sleep(2.5)
                                    print(f"'{name} heard something slowly ceeping up behind them'")
                                    print()
                                    time.sleep(2.5)
                                    print(f"'{name} turn around. Unknown creature: Scream!!'")
                                    print()
                                    time.sleep(2.5)
                                    print("'You died'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Thank you for playing the demo'")
                                    print()
                                    time.sleep(2.5)
                                    Restart = input("Enter anything to retry all demo ending")
                                    if(Restart == "") : Main()
                            else:
                                print(f"{name} made Susan cried loudly")
                                print()
                                time.sleep(2.5)
                                print(f"'{name} tried to calmed her down'")
                                print()
                                time.sleep(2.5)
                                print("Unknown creature:'Chilling cry loudly from afar in the woods")
                                print()
                                time.sleep(2.5)
                                print(f"Susan and {name}, stop all action to focus on the sound")
                                print()
                                time.sleep(2.5)
                                print(f"{name}:'What is that'")
                                print()
                                time.sleep(2.5)
                                print("In a panic, Susan stand up, and start running toward the direction Eric went looking for Derek")
                                print()
                                time.sleep(2.5)
                                print("'Type 1: Follow her'")
                                print()
                                print("'Type 2: Climb up the closest tree'")
                                print()
                                Reply = input()
                                if(Reply == "1"):
                                    print()
                                    print(f"'Susan and {name} both ran as hard as they could'")
                                    print()
                                    time.sleep(2.5)
                                    print("'But an Unknown creature catch up and slaughter them both'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Thank you for trying the demo'")
                                    print()
                                    time.sleep(2.5)
                                    Restart = input("Enter anything to retry all demo ending")
                                    if(Restart == "") : Main()
                                else:
                                    print(f"'{name} saw a huge entity passed by camp and ran toward Susan direction'")
                                    print()
                                    time.sleep(2.5)
                                    print(f"'{name} climb down and ran the opposite direction'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Thank you for playing the demo'")
                                    print()
                                    Restart = input("Enter anything to retry all demo ending")
                                    if(Restart =="") : Main()


                        else:
                            print(f"{name}: 'Derek where are you!'")
                            print()
                            time.sleep(2.5)
                            print(f"{name}: 'It's getting dark maybe I should head back'")
                            print()
                            time.sleep(2.5)
                            print(f"'{name} heard a noise of metal clanging from a distant'")
                            print()
                            time.sleep(2.5)
                            print("'Type 1: Go investigate'")
                            print()
                            print("'Type 2: Go back to camp'")
                            print()
                            Reply = input()
                            if(Reply == "1"):
                                print()
                                print(f"'{name} check the noise'")
                                print()
                                time.sleep(2.5)
                                print(f"'{name} find Derek lying on the ground. Torse torned in half.'")
                                print()
                                time.sleep(2.5)
                                print(f"{name}:'Derek! what happen'")
                                print()
                                time.sleep(2.5)
                                print("'Derek spoke softly with a dying voice'")
                                print()
                                time.sleep(2.5)
                                print("Derek:'Run'")
                                print()
                                time.sleep(2.5)
                                print("A loud unknown chilling cried from camp")
                                print()
                                time.sleep(2.5)
                                print(f"'{name} made a run for it without looking back'")
                                print()
                                time.sleep(2.5)
                                print("'Thank you for playing the demo'")
                                print()
                                time.sleep(2.5)
                                Restart = input("Enter anything to retry all demo ending")
                                if(Restart == "") : Main()
                            else:
                                print(f"'{name} got back near camp'")
                                print()
                                time.sleep(2.5)
                                print(f"'{name} see a big creature creeping up from a distant on the opposite side'")
                                print()
                                time.sleep(2.5)
                                print(f"{name}:'Run!! Something is coming up from behind!!'")
                                print()
                                time.sleep(2.5)
                                print("'Thank you for playing the demo'")
                                print()
                                time.sleep(2.5)
                                Restart = input("Enter anything to retry all demo ending")
                                if(Restart == "") : Main()

                    else:
                        print(f"'{name}, join Derek, but they went to there separate fishing spot soon after'")
                        print()
                        time.sleep(2.5)
                        print(f"'The sun is setting and {name} hasn't caught a single fish'")
                        print()
                        time.sleep(2.5)
                        print(f"{name}: 'It's getting dark'")
                        print()
                        time.sleep(2.5)
                        print(f"Type 1:{name}:' I need to head back'")
                        print()
                        print(f"Type 2:{name}:' I should go look for Derek'")
                        print()
                        Reply = input()
                        if(Reply == "1"):
                            print()
                            print(f"'{name} made it back. Camp is set up, but no one is here'")
                            print()
                            time.sleep(2.5)
                            print("'Type 1: look around'")
                            print()
                            print("'Type 2: Sit at the campfire and wait for everyone'")
                            print()
                            Reply = input()
                            if(Reply == "1"):
                                print()
                                print(f"'{name} looked arounded and saw a trail of bloods leading into the wood'")
                                print()
                                time.sleep(2.5)
                                print(f"'{name} freak out'")
                                print()
                                time.sleep(2.5)
                                print(f"{name}:'Something bad must've happened at camp'")
                                print()
                                time.sleep(2.5)
                                print("'Type 1: Go investigate'")
                                print()
                                print("'Type 2: GO back and look for Derek'")
                                print()
                                Reply = input()
                                if(Reply == "1"):
                                    print(f"'{name} See an entity munching on something'")
                                    print()
                                    time.sleep(2.5)
                                    print(f"'{name} slowly back up to camp and made a run to look for the others'")
                                    print()
                                    time.sleep(2.5)
                                    print("'You complete the demo'")
                                    print()
                                    time.sleep(2.5)
                                    Restart = input("Enter anything to start over")
                                    if(Restart == "") : Main()
                                else:
                                    print(f"{name}:'Derek, where are you!'")
                                    print()
                                    time.sleep(2.5)
                                    print(f"'{name} heard a metal noise clanging from a distance'")
                                    print()
                                    time.sleep(2.5)
                                    print("'Type 1: Go investigate'")
                                    print()
                                    print("'Type 2: Get out of here'")
                                    Reply = input()
                                    if(Reply == "1"):
                                        print()
                                        print(f"'{name} check the noise'")
                                        print()
                                        time.sleep(2.5)
                                        print(f"'{name} find Derek lying on the ground. Torse torned in half.'")
                                        print()
                                        time.sleep(2.5)
                                        print(f"{name}:'Derek! what happen'")
                                        print()
                                        time.sleep(2.5)
                                        print("'Derek spoke softly with a dying voice'")
                                        print()
                                        time.sleep(2.5)
                                        print("Derek:'Run'")
                                        print()
                                        time.sleep(2.5)
                                        print("A loud unknown chilling cried from camp")
                                        print()
                                        time.sleep(2.5)
                                        print(f"'{name} made a run for it without looking back'")
                                        print()
                                        time.sleep(2.5)
                                        print("'Thank you for playing the demo'")
                                        print()
                                        time.sleep(2.5)
                                        Restart = input("Enter anything to retry all demo ending")
                                        if(Restart == "") : Main()
                                    else:
                                        print(f"'{name} made a run for it'")
                                        print()
                                        time.sleep(2.5)
                                        print("'To be continue'")
                                        print()
                                        time.sleep(2.5)
                                        Restart = input("Enter anything to play again")
                                        if(Restart == "") : Main()
                            else:
                                print(f"'{name} waited for a while, but no has came back yet'")
                                print()
                                time.sleep(2.5)
                                print("'Darkness'")
                                print()
                                time.sleep(2.5)
                                print("'You Died'")
                                print()
                                time.sleep(2.5)
                                Restart = input("Enter anything to retry")
                                if(Restart == "") : Main()


                        else:
                            print(f"'{name} heard Derek shouting from enjoyment in a distance'")
                            print()
                            time.sleep(2.5)
                            print(f"{name}:' Derek, Let's head back!'")
                            print()
                            time.sleep(2.5)
                            print(f"'Something swiftly came by and took the light out of {name}'")
                            print()
                            time.sleep(2.5)
                            print("'Killed by an entity'")
                            print()
                            time.sleep(2.5)
                            Restart = input("Enter anything to retry")
                            if(Restart == "") : Main()

                elif(Reply == "3") :
                    print(f"'{name} ran up and round house kick Derek from behind'")
                    print()
                    time.sleep(2.5)
                    print(f"'{name} and Derek got into a brawl'")
                    print()
                    time.sleep(2.5)
                    print("'Trip got Cancel, try again another day'")
                    print()
                    time.sleep(2.5)
                    Restart = input("Enter to retry")
                    if(Restart == "") : Main()
                else:
                    print("'You left safely home'")
                    print()
                    time.sleep(2.5)
                    print("'You didn't get to enjoy the trip'")
                    print()
                    time.sleep(2.5)
                    print("'The End'")
                    print()
                    time.sleep(2.5)
                    Restart = input("'Enter to Play again'")
                    if(Restart == "") : Main()

            else:
                print("Derek:'Is this a Joke to you'")
                print()
                time.sleep(2.5)
                print(f"'Derek and {name} got into a fight")
                print()
                time.sleep(2.5)
                print("'The trip is canceled. You Failed'")
                print()
                time.sleep(2.5)
                Restart= input("'Enter to retry'")
                if(Restart == "") : Main()
        else:
            print("Seems like you're not ready...")
            print()
            time.sleep(2.5)
            print(f"{name}, you let your friends down!!")
            print()
            time.sleep(2.5)
            print("COMEBACK WHEN YOU'RE READY!!")
            print()
            #pause
            Restart = input("'Enter anything to go back to the menu'")
            if(Restart == "") : Main() 
            else: exit()
Main()